export const projects = [
  {
    slug: 'taidekerho',
    title: 'Community Art Club',
    subtitle: 'Taidekerho',
    location: 'Jyväskylä, Finland',
    period: 'Aug 2025 – Present',
    status: 'Ongoing',
    description:
      'A weekly, free, open-door creative space I founded at Aseman Pysäkki — growing from zero to 50+ participants across 12 nationalities in six months.',
    tags: ['Community', 'Facilitation', 'Coordination'],
    // Palette: mustard warmth
    accent: '#F2E6D4',
    accentBorder: '#E8D4B8',
    tagBg: 'rgba(193,165,119,0.12)',
    tagColor: '#9A7F55',
    statusBg: 'rgba(193,165,119,0.18)',
    icon: '🎨',
    featured: true,
    stats: [
      { icon: '👥', label: 'Participants', value: '50+' },
      { icon: '🌍', label: 'Nationalities', value: '12' },
      { icon: '📅', label: 'Frequency', value: 'Weekly' },
      { icon: '⏱', label: 'Running since', value: 'Aug 2025' },
    ],
    timeline: [
      { year: 'Aug 2025', label: 'Club Founded', icon: '🌱' },
      { year: 'Sep 2025', label: 'First Sessions', icon: '🎨' },
      { year: 'Nov 2025', label: '50+ Members', icon: '👥' },
      { year: 'Dec 2025', label: 'Christmas Event', icon: '🎄' },
      { year: '2026', label: 'Ongoing', icon: '✨' },
    ],
    gallery: [
      { label: 'Weekly session', color: '#F2E6D4' },
      { label: 'Art materials', color: '#EDD9C0' },
      { label: 'Community table', color: '#F7EDE0' },
      { label: 'Participants', color: '#E8D4B8' },
      { label: 'Art display', color: '#F4E8D8' },
      { label: 'Christmas event', color: '#EFDCC8' },
    ],
    fullDescription:
      'A weekly, free, open-door creative community space I founded and continue to run at Aseman Pysäkki. The club grew from zero to 50+ participants across 11–12 nationalities within six months, spanning ages 2 to elderly. Every session is themed and facilitated by me — I handle the full coordination cycle: planning, sourcing materials, communicating with participants, adapting formats for accessibility, and maintaining the welcoming atmosphere that keeps people coming back. We have organised a community art exhibition and multicultural celebration events alongside the weekly sessions. Supported by Jyväskylän Seurakunta, the club also contributes to Christmas community events and facilitates social integration for local and international visitors.',
  },
  {
    slug: 'blog-social-media',
    title: 'International Life in Jyväskylä',
    subtitle: 'Blog & Social Media',
    location: 'Jyväskylä, Finland',
    period: '2024 – Present',
    status: 'Ongoing',
    description:
      'Writing and social media content documenting the realities of international life in Finland — practical guides for newcomers navigating Finnish systems.',
    tags: ['Writing', 'Social Media', 'Integration'],
    // Palette: lavender
    accent: '#E8E6F0',
    accentBorder: '#D4D0E4',
    tagBg: 'rgba(197,195,208,0.18)',
    tagColor: '#7A78A0',
    statusBg: 'rgba(197,195,208,0.25)',
    icon: '✍️',
    featured: true,
    stats: [
      { icon: '📝', label: 'Content type', value: 'Blog & Social' },
      { icon: '🌐', label: 'Audience', value: 'Newcomers' },
      { icon: '🇫🇮', label: 'Focus', value: 'Finland life' },
      { icon: '⏱', label: 'Since', value: '2024' },
    ],
    timeline: [
      { year: '2024', label: 'First posts', icon: '✍️' },
      { year: '2024', label: 'Finnish guides', icon: '🇫🇮' },
      { year: '2025', label: 'Growing reach', icon: '📈' },
      { year: '2026', label: 'Ongoing', icon: '✨' },
    ],
    gallery: [
      { label: 'Blog post', color: '#E8E6F0' },
      { label: 'Social content', color: '#DDD9EE' },
      { label: 'Finnish guide', color: '#EDEAF5' },
      { label: 'City life', color: '#E4E2EE' },
      { label: 'Community', color: '#E0DDE8' },
      { label: 'Integration tips', color: '#EAE8F2' },
    ],
    fullDescription:
      'Writing and social media content documenting the realities of international life in Finland — practical guides for newcomers navigating Finnish systems, bureaucracy, culture, and community. Created to fill a gap I noticed personally as someone who relocated to Jyväskylä from Bangladesh: honest, human, non-institutional guidance for people trying to build a life in Finland.',
  },
  {
    slug: 'instagram-art-community',
    title: 'Instagram Art Community',
    subtitle: '@priyodorshini.d_',
    location: 'Global',
    period: '2019 – Present',
    status: 'Ongoing',
    description:
      'Built an engaged international creative community of 15,000+ followers through consistent original drawing and painting content — entirely organic growth.',
    tags: ['Social Media', 'Creative', 'Community Building'],
    // Palette: pink
    accent: '#EDE0E2',
    accentBorder: '#DED0D2',
    tagBg: 'rgba(186,167,170,0.15)',
    tagColor: '#8E7478',
    statusBg: 'rgba(186,167,170,0.2)',
    icon: '🖼️',
    featured: true,
    callToAction: { label: 'Visit @priyodorshini.d_ on Instagram', href: 'https://instagram.com/priyodorshini.d_', icon: '📸' },
    stats: [
      { icon: '❤️', label: 'Followers', value: '15K+' },
      { icon: '🌍', label: 'Reach', value: 'Global' },
      { icon: '📈', label: 'Growth', value: 'Organic' },
      { icon: '🖌️', label: 'Medium', value: 'Drawing & Painting' },
    ],
    timeline: [
      { year: '2019', label: 'Account started', icon: '🌱' },
      { year: '2020', label: 'Consistent posting', icon: '🖌️' },
      { year: '2021', label: '5K followers', icon: '📈' },
      { year: '2023', label: '10K milestone', icon: '🎉' },
      { year: '2025', label: '15K+ followers', icon: '🌍' },
    ],
    gallery: [
      { label: 'Drawing post', color: '#EDE0E2' },
      { label: 'Painting', color: '#E4D8DA' },
      { label: 'Community art', color: '#F0E6E8' },
      { label: 'Process shot', color: '#E8DDE0' },
      { label: 'Finished piece', color: '#EAE0E2' },
      { label: 'Sketchbook', color: '#E6DCDE' },
    ],
    fullDescription:
      'Built an engaged international creative community of 15,000+ followers through consistent original drawing and painting content, entirely through organic growth with no paid promotion. The account — @priyodorshini.d_ — demonstrates sustained commitment to art as a vehicle for human connection, and has grown into a creative community spanning many countries. Every piece of content is original, handmade, and personally meaningful.',
  },
  {
    slug: 'urban-forestation',
    title: 'Urban Forestation Campaign',
    subtitle: 'Co-organiser',
    location: 'Dhaka, Bangladesh',
    period: '2018 – 2022',
    status: 'Completed',
    description:
      'Planted 400+ trees in schoolyards, rooftops and community spaces through locally raised funds, alongside environmental awareness sessions in schools.',
    tags: ['Environment', 'Grassroots', 'Community'],
    // Palette: soft green-mustard mix
    accent: '#DFF0DF',
    accentBorder: '#CCE4CC',
    tagBg: 'rgba(150,190,150,0.14)',
    tagColor: '#5A825A',
    statusBg: 'rgba(193,165,119,0.12)',
    icon: '🌱',
    featured: false,
    stats: [
      { icon: '🌳', label: 'Trees planted', value: '400+' },
      { icon: '🏫', label: 'Locations', value: 'Schools & rooftops' },
      { icon: '💰', label: 'Funding', value: 'Locally raised' },
      { icon: '📅', label: 'Duration', value: '4 years' },
    ],
    timeline: [
      { year: '2018', label: 'Campaign started', icon: '🌱' },
      { year: '2019', label: 'School sessions', icon: '🏫' },
      { year: '2020', label: '100+ trees', icon: '🌳' },
      { year: '2021', label: 'Rooftop gardens', icon: '🏠' },
      { year: '2022', label: '400+ trees total', icon: '🏆' },
    ],
    gallery: [
      { label: 'Tree planting', color: '#DFF0DF' },
      { label: 'School session', color: '#D4EAD4' },
      { label: 'Rooftop garden', color: '#E4F2E4' },
      { label: 'Community group', color: '#D8ECD8' },
      { label: 'Seedlings', color: '#E0F0E0' },
      { label: 'Awareness event', color: '#DCEEDC' },
    ],
    fullDescription:
      'Co-organised a grassroots urban forestation campaign that planted 400+ trees in schoolyards, rooftops, and community spaces across Dhaka through locally raised funds. The campaign was built around practical action and community education: we ran environmental awareness sessions in schools and guided families on how to grow plants on rooftops and balconies — making greening accessible even in a dense urban environment. Everything was done without institutional backing, driven entirely by community commitment and peer-to-peer fundraising.',
  },
  {
    slug: 'street-children-night-school',
    title: 'Street Children Night School',
    subtitle: 'Co-founder',
    location: 'Dhaka, Bangladesh',
    period: '2018 – 2022',
    status: 'Completed',
    description:
      'Co-founded informal evening lessons for working and out-of-school children in slum areas of Dhaka, sustained for five years alongside university studies.',
    tags: ['Education', 'Grassroots', 'Youth'],
    // Palette: warm pink
    accent: '#F5E4DE',
    accentBorder: '#EAD4CC',
    tagBg: 'rgba(186,167,170,0.12)',
    tagColor: '#8E7478',
    statusBg: 'rgba(193,165,119,0.1)',
    icon: '📚',
    featured: false,
    stats: [
      { icon: '👧', label: 'Beneficiaries', value: 'Children' },
      { icon: '👩‍🎓', label: 'Co-founders', value: '6 students' },
      { icon: '🕯️', label: 'Sessions', value: 'Evening, weekly' },
      { icon: '📅', label: 'Sustained for', value: '5 years' },
    ],
    timeline: [
      { year: '2018', label: 'School founded', icon: '🌱' },
      { year: '2019', label: 'Regular sessions', icon: '📚' },
      { year: '2020', label: 'Community outreach', icon: '🤝' },
      { year: '2021', label: 'Continued through studies', icon: '🎓' },
      { year: '2022', label: '5 years completed', icon: '🏆' },
    ],
    gallery: [
      { label: 'Evening session', color: '#F5E4DE' },
      { label: 'Children learning', color: '#F0DCD4' },
      { label: 'Outreach visit', color: '#FAEEE8' },
      { label: 'Classroom setup', color: '#F2E0DA' },
      { label: 'Group activity', color: '#F5E6E0' },
      { label: 'Community area', color: '#EED8D0' },
    ],
    fullDescription:
      'Co-founded and sustained informal evening lessons for working and out-of-school children in slum areas of Dhaka for five years, together with six fellow university students. We ran sessions around the children\'s own schedules and availability — outreaching directly in the community to reach those who needed it most. There was no institutional backing, no funding: only a shared commitment to making access to education more equitable. Sustaining the school for five years through our own degree programmes and employment speaks to the kind of consistency and care I bring to work I believe in.',
  },
]
